# Generated by Django 5.2.5 on 2025-09-06 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientID', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=50)),
                ('Coordonnees', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('UtilisateurID', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('ContratID', models.AutoField(primary_key=True, serialize=False)),
                ('DateSignature', models.DateField()),
                ('Statut', models.CharField(max_length=50)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('EvenementID', models.AutoField(primary_key=True, serialize=False)),
                ('NomEvenement', models.CharField(max_length=100)),
                ('DateDebut', models.DateField()),
                ('DateFin', models.DateField()),
                ('Statut', models.CharField(max_length=50)),
                ('Contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='api.contrat')),
            ],
        ),
        migrations.CreateModel(
            name='EquipeSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Responsable', models.BooleanField(default=False)),
                ('Evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evenement')),
                ('Utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur')),
            ],
            options={
                'unique_together': {('Utilisateur', 'Evenement')},
            },
        ),
    ]
